// <auto-generated />
using System;
using GenericWebApp.Model.Music;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenericWebApp.Model.Migrations
{
    [DbContext(typeof(AlbumContext))]
    [Migration("20250124045243_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GenericWebApp.Model.Music.Album", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID");

                    b.ToTable("Music_Album");
                });

            modelBuilder.Entity("GenericWebApp.Model.Music.CD", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("AlbumID")
                        .HasColumnType("int");

                    b.Property<int?>("Album_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Genre_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Label_ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID");

                    b.HasIndex("AlbumID");

                    b.HasIndex("Label_ID");

                    b.ToTable("Music_CD");
                });

            modelBuilder.Entity("GenericWebApp.Model.Music.Genre", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("LabelID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LabelID");

                    b.ToTable("Music_Genre");
                });

            modelBuilder.Entity("GenericWebApp.Model.Music.Label", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime?>("Defunct")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Founded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Founder")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID");

                    b.ToTable("Music_Label");
                });

            modelBuilder.Entity("GenericWebApp.Model.Music.Label_Genre", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Genre_ID")
                        .HasColumnType("int");

                    b.Property<int>("Label_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Genre_ID");

                    b.HasIndex("Label_ID");

                    b.ToTable("Music_Label_Genre");
                });

            modelBuilder.Entity("GenericWebApp.Model.Music.Track", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("CDID")
                        .HasColumnType("int");

                    b.Property<int>("CD_ID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("time");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID");

                    b.HasIndex("CDID");

                    b.ToTable("Music_Track");
                });

            modelBuilder.Entity("GenericWebApp.Model.Music.CD", b =>
                {
                    b.HasOne("GenericWebApp.Model.Music.Album", null)
                        .WithMany("CDList")
                        .HasForeignKey("AlbumID");

                    b.HasOne("GenericWebApp.Model.Music.Label", "LabelObj")
                        .WithMany()
                        .HasForeignKey("Label_ID");

                    b.Navigation("LabelObj");
                });

            modelBuilder.Entity("GenericWebApp.Model.Music.Genre", b =>
                {
                    b.HasOne("GenericWebApp.Model.Music.Label", null)
                        .WithMany("GenreList")
                        .HasForeignKey("LabelID");
                });

            modelBuilder.Entity("GenericWebApp.Model.Music.Label_Genre", b =>
                {
                    b.HasOne("GenericWebApp.Model.Music.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("Genre_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenericWebApp.Model.Music.Label", "Label")
                        .WithMany()
                        .HasForeignKey("Label_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Label");
                });

            modelBuilder.Entity("GenericWebApp.Model.Music.Track", b =>
                {
                    b.HasOne("GenericWebApp.Model.Music.CD", null)
                        .WithMany("TrackList")
                        .HasForeignKey("CDID");
                });

            modelBuilder.Entity("GenericWebApp.Model.Music.Album", b =>
                {
                    b.Navigation("CDList");
                });

            modelBuilder.Entity("GenericWebApp.Model.Music.CD", b =>
                {
                    b.Navigation("TrackList");
                });

            modelBuilder.Entity("GenericWebApp.Model.Music.Label", b =>
                {
                    b.Navigation("GenreList");
                });
#pragma warning restore 612, 618
        }
    }
}
