// <auto-generated />
using System;
using GenericWebApp.Model.Music;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenericWebApp.Model.Migrations
{
    [DbContext(typeof(AlbumContext))]
    [Migration("20250128013441_migrationUpdatingFK1")]
    partial class migrationUpdatingFK1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GenericWebApp.Model.Music.Album", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID");

                    b.HasIndex("ArtistName");

                    b.ToTable("Music_Album");
                });

            modelBuilder.Entity("GenericWebApp.Model.Music.CD", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("Album_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Genre_ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID");

                    b.HasIndex("Album_ID");

                    b.HasIndex("Name");

                    b.ToTable("Music_CD");
                });

            modelBuilder.Entity("GenericWebApp.Model.Music.Genre", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID");

                    b.ToTable("Music_Genre");
                });

            modelBuilder.Entity("GenericWebApp.Model.Music.Track", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CD_ID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("time");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID");

                    b.HasIndex("CD_ID");

                    b.HasIndex("Title");

                    b.ToTable("Music_Track");
                });

            modelBuilder.Entity("GenericWebApp.Model.Music.CD", b =>
                {
                    b.HasOne("GenericWebApp.Model.Music.Album", "Album")
                        .WithMany("CDList")
                        .HasForeignKey("Album_ID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Album");
                });

            modelBuilder.Entity("GenericWebApp.Model.Music.Track", b =>
                {
                    b.HasOne("GenericWebApp.Model.Music.CD", "CD")
                        .WithMany("TrackList")
                        .HasForeignKey("CD_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CD");
                });

            modelBuilder.Entity("GenericWebApp.Model.Music.Album", b =>
                {
                    b.Navigation("CDList");
                });

            modelBuilder.Entity("GenericWebApp.Model.Music.CD", b =>
                {
                    b.Navigation("TrackList");
                });
#pragma warning restore 612, 618
        }
    }
}
